version: '2.4'

volumes:
  public: ~
  mysqldb_data: ~

services:
  nginx:
    image: nginx
    volumes:
      - ./vhost.conf:/etc/nginx/conf.d/default.conf
      - public:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      php:
        condition: service_started
  php:
    build:
      context: .
      target: dev
    volumes:
      - .:/var/www/html
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    image: mysql:8
    healthcheck:
      test: ["CMD-SHELL", "bash", "-c", "echo > /dev/tcp/localhost/3306"]
      interval: 1s
    volumes:
      - mysqldb_data:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - "3306:3306"
